include ./shared.conf

port: 4226
http_port: 8226
server_name: c2-n2

jetstream {
  store_dir: "./data/c2-n2/js"
  max_mem: 0
  max_file: 10GB
}

cluster: {
  name: c2,
  port: 6226,
  routes: [
    "nats-route://0.0.0.0:6225",
    "nats-route://0.0.0.0:6226",
    "nats-route://0.0.0.0:6227"
  ],
}

gateway: {
  name: "c2",
  port: 7226,
  gateways: [
    {name: "c1", urls: ["nats://0.0.0.0:7222"]},
    {name: "c2", urls: ["nats://0.0.0.0:7225"]},
    {name: "c3", urls: ["nats://0.0.0.0:7228"]},
  ]
}
