port: 5005
http_port: 9005
server_name: c3-l4

include "./shared.conf"

jetstream {
  store_dir: "./data/c3-l4/js"
  max_mem: 0
  max_file: 10GB
}

leafnodes: {
  remotes: [
    {
      urls: [
        "nats-leaf://0.0.0.0:7406",
        "nats-leaf://0.0.0.0:7407",
        "nats-leaf://0.0.0.0:7408"
      ]
      account: "APP"
    }
  ]
}
