include ./shared.conf

port: 4230
http_port: 8230
server_name: c3-n3

jetstream {
  store_dir: "./data/c3-n3/js"
  max_mem: 0
  max_file: 10GB
}

cluster: {
  name: c3,
  port: 6230,
  routes: [
    "nats-route://0.0.0.0:6228",
    "nats-route://0.0.0.0:6229",
    "nats-route://0.0.0.0:6230"
  ],
}

gateway: {
  name: "c3",
  port: 7230,
  gateways: [
    {name: "c1", urls: ["nats://0.0.0.0:7222"]},
    {name: "c2", urls: ["nats://0.0.0.0:7225"]},
    {name: "c3", urls: ["nats://0.0.0.0:7228"]},
  ]
}

leafnodes: {
  port: 7408
}
