include ../shared.conf

port: 4222
http_port: 8222
server_name: n1

jetstream {
  store_dir: "./data/cluster/n1/js"
  max_mem: 0
  max_file: 10GB
}

cluster: {
  name: cluster,
  port: 6222,
  routes: [
    "nats-route://0.0.0.0:6222",
    "nats-route://0.0.0.0:6223",
    "nats-route://0.0.0.0:6224"
  ],
}
