include ../shared.conf

port: 4223
http_port: 8223
server_name: n2

jetstream {
  store_dir: "./data/cluster/n2/js"
  max_mem: 0
  max_file: 10GB
}

cluster: {
  name: cluster,
  port: 6223,
  routes: [
    "nats-route://0.0.0.0:6222",
    "nats-route://0.0.0.0:6223",
    "nats-route://0.0.0.0:6224"
  ],
}
