include ./shared.conf

port: 4250
http_port: 8250
server_name: east

jetstream {
  domain: east
  store_dir: "./data/east/js"
  max_mem: 0
  max_file: 1GB
}

gateway {
  name: "east"
  port: 7250
  gateways: [
    {name: "east", urls: ["nats://0.0.0.0:7250"]},
    {name: "west", urls: ["nats://0.0.0.0:7251"]},
  ]
}
