include ./shared.conf

port: 4251
http_port: 8251
server_name: west

jetstream {
  domain: west
  store_dir: "./data/west/js"
  max_mem: 0
  max_file: 1GB
}

gateway {
  name: "west"
  port: 7251
  gateways: [
    {name: "east", urls: ["nats://0.0.0.0:7250"]},
    {name: "west", urls: ["nats://0.0.0.0:7251"]},
  ]
}
