include ../shared.conf

port: 5007
http_port: 9000
server_name: c1-l1

jetstream {
  store_dir: "./data/super/c1-l1/js"
  max_mem: 0
  max_file: 10GB
}

leafnodes: {
  isolate: true

  remotes: [
    {
      urls: [
        "nats-leaf://0.0.0.0:7400",
        "nats-leaf://0.0.0.0:7401",
        "nats-leaf://0.0.0.0:7402"
      ]
      account: "APP"
    }
  ]
}
