include ../shared.conf

port: 4224
http_port: 8224
server_name: c1-n3

jetstream {
  store_dir: "./data/super/c1-n3/js"
  max_mem: 0
  max_file: 10GB
}

cluster: {
  name: c1,
  port: 6224,
  routes: [
    "nats-route://0.0.0.0:6222",
    "nats-route://0.0.0.0:6223",
    "nats-route://0.0.0.0:6224"
  ],
}

gateway: {
  name: "c1",
  port: 7224,
  gateways: [
    {name: "c1", urls: ["nats://0.0.0.0:7222"]},
    {name: "c2", urls: ["nats://0.0.0.0:7225"]},
    {name: "c3", urls: ["nats://0.0.0.0:7228"]},
  ]
}

leafnodes: {
  port: 7402
}
