include ../shared.conf

port: 4227
http_port: 8227
server_name: c2-n3

jetstream {
  store_dir: "./data/super/c2-n3/js"
  max_mem: 0
  max_file: 10GB
}

cluster: {
  name: c2,
  port: 6227,
  routes: [
    "nats-route://0.0.0.0:6225",
    "nats-route://0.0.0.0:6226",
    "nats-route://0.0.0.0:6227"
  ],
}

gateway: {
  name: "c2",
  port: 7227,
  gateways: [
    {name: "c1", urls: ["nats://0.0.0.0:7222"]},
    {name: "c2", urls: ["nats://0.0.0.0:7225"]},
    {name: "c3", urls: ["nats://0.0.0.0:7228"]},
  ]
}
