include ../shared.conf

port: 5003
http_port: 9003
server_name: c3-l2

jetstream {
  store_dir: "./data/super/c3-l2/js"
  max_mem: 0
  max_file: 10GB
}

leafnodes: {
  remotes: [
    {
      urls: [
        "nats-leaf://0.0.0.0:7406",
        "nats-leaf://0.0.0.0:7407",
        "nats-leaf://0.0.0.0:7408"
      ]
      account: "APP"
    }
  ]
}
